// Chain3Go project rpcName.go
package Chain3Go

//jsonRPC名
const (
	CHAIN3_clientVersion = "chain3_clientVersion"
	CHAIN3_sha3          = "chain3_sha3"

	NET_version   = "net_version"
	NET_peerCount = "net_peerCount"
	NET_listening = "net_listening"

	MC_protocolVersion                     = "mc_protocolVersion"
	MC_syncing                             = "mc_syncing"
	MC_coinbase                            = "mc_coinbase"
	MC_mining                              = "mc_mining"
	MC_hashrate                            = "mc_hashrate"
	MC_gasPrice                            = "mc_gasPrice"
	MC_accounts                            = "mc_accounts"
	MC_blockNumber                         = "mc_blockNumber"
	MC_getBalance                          = "mc_getBalance"
	MC_getStorageAt                        = "mc_getStorageAt"
	MC_getTransactionCount                 = "mc_getTransactionCount"
	MC_getBlockTransactionCountByHash      = "mc_getBlockTransactionCountByHash"
	MC_getBlockTransactionCountByNumber    = "mc_getBlockTransactionCountByNumber"
	MC_getUncleCountByBlockHash            = "mc_getUncleCountByBlockHash"
	MC_getUncleCountByBlockNumber          = "mc_getUncleCountByBlockNumber"
	MC_getCode                             = "mc_getCode"
	MC_sign                                = "mc_sign"
	MC_sendTransaction                     = "mc_sendTransaction"
	MC_sendRawTransaction                  = "mc_sendRawTransaction"
	MC_call                                = "mc_call"
	MC_estimateGas                         = "mc_estimateGas"
	MC_getBlockByHash                      = "mc_getBlockByHash"
	MC_getBlockByNumber                    = "mc_getBlockByNumber"
	MC_getTransactionByHash                = "mc_getTransactionByHash"
	MC_getTransactionByBlockHashAndIndex   = "mc_getTransactionByBlockHashAndIndex"
	MC_getTransactionByBlockNumberAndIndex = "mc_getTransactionByBlockNumberAndIndex"
	MC_getTransactionReceipt               = "mc_getTransactionReceipt"
	MC_getUncleByBlockHashAndIndex         = "mc_getUncleByBlockHashAndIndex"
	MC_getUncleByBlockNumberAndIndex       = "mc_getUncleByBlockNumberAndIndex"
	MC_newFilter                           = "mc_newFilter"
	MC_newBlockFilter                      = "mc_newBlockFilter"
	MC_newPendingTransactionFilter         = "mc_newPendingTransactionFilter"
	MC_uninstallFilter                     = "mc_uninstallFilter"
	MC_getFilterChanges                    = "mc_getFilterChanges"
	MC_getFilterLogs                       = "mc_getFilterLogs"
	MC_getLogs                             = "mc_getLogs"
	MC_getWork                             = "mc_getWork"
	MC_submitWork                          = "mc_submitWork"

	VNODE_address      = "vnode_address"
	VNODE_scsService   = "vnode_scsService"
	VNODE_serviceCfg   = "vnode_serviceCfg"
	VNODE_showToPublic = "vnode_showToPublic"
	VNODE_vnodeIP      = "vnode_vnodeIP"

	SCS_directCall            = "scs_directCall"
	SCS_getBlock              = "scs_getBlock"
	SCS_getBlockNumber        = "scs_getBlockNumber"
	SCS_getDappState          = "scs_getDappState"
	SCS_getMicroChainList     = "scs_getMicroChainList"
	SCS_getNonce              = "scs_getNonce"
	SCS_getSCSId              = "scs_getSCSId"
	SCS_getTransactionReceipt = "scs_getTransactionReceipt"

	PERSONAL_unlockAccount   = "personal_unlockAccount"
	PERSONAL_lockAccount     = "personal_lockAccount"
	PERSONAL_newAccount      = "personal_newAccount"
	PERSONAL_sign            = "personal_sign"
	PERSONAL_ecRecover       = "personal_ecRecover"
	PERSONAL_sendTransaction = "personal_sendTransaction"

	ScsRPCMethod_GetBalance     = "ScsRPCMethod.GetBalance"
	ScsRPCMethod_GetNonce       = "ScsRPCMethod.GetNonce"
	ScsRPCMethod_GetBlockNumber = "ScsRPCMethod.GetBlockNumber"
)
